<?php

namespace ContainerD80mavg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_U1VJIFVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.u1VJIFV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.u1VJIFV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'agentRepository' => ['privates', 'App\\Repository\\AgentRepository', 'getAgentRepositoryService', true],
            'officeRepository' => ['privates', 'App\\Repository\\OfficeRepository', 'getOfficeRepositoryService', true],
        ], [
            'agentRepository' => 'App\\Repository\\AgentRepository',
            'officeRepository' => 'App\\Repository\\OfficeRepository',
        ]);
    }
}
