<?php

namespace ContainerD80mavg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_H6QpXQLService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.h6QpXQL' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.h6QpXQL'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'driverRepository' => ['privates', 'App\\Repository\\DriverRepository', 'getDriverRepositoryService', true],
        ], [
            'driverRepository' => 'App\\Repository\\DriverRepository',
        ]);
    }
}
