<?php

namespace ContainerD80mavg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I8OPE8nService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.I8OPE8n' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.I8OPE8n'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'rateRepository' => ['privates', 'App\\Repository\\RateRepository', 'getRateRepositoryService', true],
        ], [
            'rateRepository' => 'App\\Repository\\RateRepository',
        ]);
    }
}
