<?php

namespace ContainerD80mavg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XqNfBRsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XqNfBRs' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XqNfBRs'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'parkingspot' => ['privates', '.errored..service_locator.XqNfBRs.App\\Entity\\Destination\\Parkingspot', NULL, 'Cannot autowire service ".service_locator.XqNfBRs": it needs an instance of "App\\Entity\\Destination\\Parkingspot" but this type has been excluded in "config/services.yaml".'],
        ], [
            'parkingspot' => 'App\\Entity\\Destination\\Parkingspot',
        ]);
    }
}
