<?php

namespace ContainerD80mavg;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFavorite2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.mzq3sMF.App\Entity\Destination\Favorite' shared service.
     *
     * @return \App\Entity\Destination\Favorite
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.mzq3sMF": it needs an instance of "App\\Entity\\Destination\\Favorite" but this type has been excluded in "config/services.yaml".');
    }
}
