knp_snappy:
    
      pdf:
        binary: '/usr/bin/wkhtmltopdf'
        options:
            enable-local-file-access: true
            
      image:
        enabled:    true
        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
