knp_snappy:
    
      pdf:
        binary: 'C:\PROGRA~1\wkhtmltopdf\bin\wkhtmltopdf.exe'
        options:
            enable-local-file-access: true
            
      image:
        enabled:    true
        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
