payum:
    security:
        token_storage:
            App\Entity\PayumSecurityToken:
                doctrine:
                    driver: orm

    storages:
        App\Entity\Payment:
            doctrine:
                driver: orm


    gateways:
        stripe_checkout:
            factory: stripe_checkout
            publishable_key: '%env(STRIPE_PUBLISHABLE_KEY)%'
            secret_key: '%env(STRIPE_SECRET_KEY)%'
            payment_method_types: ['Card']
            line_items: true
            mode: payment
            success_url: '%env(APP_URL)%/payment/done?session_id={CHECKOUT_SESSION_ID}'
            cancel_url: '%env(APP_URL)%/payment/cancel'
