security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
        App\Entity\User:
            algorithm: auto

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    enable_authenticator_manager: true
    
    # Session configuration for all firewalls
    session_fixation_strategy: migrate # Prevents session fixation attacks
    hide_user_not_found: true # Improves security
    
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            custom_authenticators:
                - App\Security\LoginFormAuthenticator
                - App\Security\GoogleAuthenticator
            
            logout:
                path: app_logout
                target: app_front_home
                invalidate_session: true
                
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week
                path: /
                always_remember_me: false
                
            # Custom security handlers
            access_denied_handler: App\Security\AccessDeniedHandler
            entry_point: App\Security\AuthenticationEntryPoint

    # Role hierarchy
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # Access control
    access_control:
        # Front office (public) routes
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/services$, roles: PUBLIC_ACCESS }
        - { path: ^/portfolio$, roles: PUBLIC_ACCESS }
        - { path: ^/contact$, roles: PUBLIC_ACCESS }
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/register, roles: PUBLIC_ACCESS }
        - { path: ^/reset-password, roles: PUBLIC_ACCESS }
        - { path: ^/verify, roles: PUBLIC_ACCESS }
        - { path: ^/forgot-password, roles: PUBLIC_ACCESS }
        - { path: ^/check-banned, roles: PUBLIC_ACCESS }
        - { path: ^/connect/google$, roles: PUBLIC_ACCESS }
        - { path: ^/connect/google/check$, roles: PUBLIC_ACCESS }
        - { path: ^/connect/google/failure$, roles: PUBLIC_ACCESS }
        - { path: ^/sign-language-translation$, roles: PUBLIC_ACCESS }
        
        # Event related routes
        - { path: ^/event, roles: PUBLIC_ACCESS }
        - { path: ^/event/\d+$, roles: PUBLIC_ACCESS }
        - { path: ^/event/show/\d+$, roles: PUBLIC_ACCESS }
        
        # Destination related routes
        - { path: ^/destination, roles: PUBLIC_ACCESS }
        - { path: ^/destination/cards, roles: PUBLIC_ACCESS }
        
        # Transport related routes
        - { path: ^/transport, roles: PUBLIC_ACCESS }
        - { path: ^/transport/list, roles: PUBLIC_ACCESS }
        - { path: ^/transport/show, roles: PUBLIC_ACCESS }
        
        # Agent related routes
        - { path: ^/agent, roles: PUBLIC_ACCESS }
        - { path: ^/agent/list, roles: PUBLIC_ACCESS }
        - { path: ^/agent/\d+$, roles: PUBLIC_ACCESS }
        
        # PDF and download routes
        - { path: ^/pdf, roles: PUBLIC_ACCESS }
        - { path: ^/download, roles: PUBLIC_ACCESS }
        - { path: ^/generate, roles: PUBLIC_ACCESS }
        - { path: ^/export, roles: PUBLIC_ACCESS }
        - { path: ^/print, roles: PUBLIC_ACCESS }
        
        # Reservation public routes
        # Reservation routes require authentication
        - { path: ^/reservation/new, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/reservation/confirm, roles: [ROLE_USER, ROLE_ADMIN] }
        
        # Static resources and assets
        - { path: ^/uploads, roles: PUBLIC_ACCESS }
        - { path: ^/assets, roles: PUBLIC_ACCESS }
        - { path: ^/img, roles: PUBLIC_ACCESS }
        - { path: ^/js, roles: PUBLIC_ACCESS }
        - { path: ^/css, roles: PUBLIC_ACCESS }
        - { path: ^/vendor, roles: PUBLIC_ACCESS }
        
        # Back office (dashboard) routes
        - { path: ^/dashboard, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: ROLE_USER }
        - { path: ^/claims, roles: ROLE_USER }
        # General reservation access control
        - { path: ^/reservation, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
