vich_uploader:
    db_driver: orm

    mappings:
        destination_images:
            uri_prefix: /uploads/destinations
            upload_destination: '%kernel.project_dir%/public/uploads/destinations'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
