<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class User extends \App\Entity\User implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'avatar' => [parent::class, 'avatar', null],
        "\0".parent::class."\0".'banExpiryDate' => [parent::class, 'banExpiryDate', null],
        "\0".parent::class."\0".'banReason' => [parent::class, 'banReason', null],
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null],
        "\0".parent::class."\0".'faceIdEnabled' => [parent::class, 'faceIdEnabled', null],
        "\0".parent::class."\0".'firstName' => [parent::class, 'firstName', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'isBanned' => [parent::class, 'isBanned', null],
        "\0".parent::class."\0".'lastLogin' => [parent::class, 'lastLogin', null],
        "\0".parent::class."\0".'lastName' => [parent::class, 'lastName', null],
        "\0".parent::class."\0".'password' => [parent::class, 'password', null],
        "\0".parent::class."\0".'reclamations' => [parent::class, 'reclamations', null],
        "\0".parent::class."\0".'role' => [parent::class, 'role', null],
        'avatar' => [parent::class, 'avatar', null],
        'banExpiryDate' => [parent::class, 'banExpiryDate', null],
        'banReason' => [parent::class, 'banReason', null],
        'created_at' => [parent::class, 'created_at', null],
        'email' => [parent::class, 'email', null],
        'faceIdEnabled' => [parent::class, 'faceIdEnabled', null],
        'firstName' => [parent::class, 'firstName', null],
        'id' => [parent::class, 'id', null],
        'isBanned' => [parent::class, 'isBanned', null],
        'lastLogin' => [parent::class, 'lastLogin', null],
        'lastName' => [parent::class, 'lastName', null],
        'password' => [parent::class, 'password', null],
        'reclamations' => [parent::class, 'reclamations', null],
        'role' => [parent::class, 'role', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
