<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Reservation extends \App\Entity\Reservation implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'agent' => [parent::class, 'agent', null],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null],
        "\0".parent::class."\0".'date' => [parent::class, 'date', null],
        "\0".parent::class."\0".'destination' => [parent::class, 'destination', null],
        "\0".parent::class."\0".'driver' => [parent::class, 'driver', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'location' => [parent::class, 'location', null],
        "\0".parent::class."\0".'paymentMode' => [parent::class, 'paymentMode', null],
        "\0".parent::class."\0".'seats' => [parent::class, 'seats', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'tickets' => [parent::class, 'tickets', null],
        "\0".parent::class."\0".'transport' => [parent::class, 'transport', null],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null],
        "\0".parent::class."\0".'user' => [parent::class, 'user', null],
        'agent' => [parent::class, 'agent', null],
        'createdAt' => [parent::class, 'createdAt', null],
        'date' => [parent::class, 'date', null],
        'destination' => [parent::class, 'destination', null],
        'driver' => [parent::class, 'driver', null],
        'id' => [parent::class, 'id', null],
        'location' => [parent::class, 'location', null],
        'paymentMode' => [parent::class, 'paymentMode', null],
        'seats' => [parent::class, 'seats', null],
        'status' => [parent::class, 'status', null],
        'tickets' => [parent::class, 'tickets', null],
        'transport' => [parent::class, 'transport', null],
        'updatedAt' => [parent::class, 'updatedAt', null],
        'user' => [parent::class, 'user', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
