<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Transport extends \App\Entity\Transport implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'Capacity' => [parent::class, 'Capacity', null],
        "\0".parent::class."\0".'Type' => [parent::class, 'Type', null],
        "\0".parent::class."\0".'destination' => [parent::class, 'destination', null],
        "\0".parent::class."\0".'disponibility' => [parent::class, 'disponibility', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        'Capacity' => [parent::class, 'Capacity', null],
        'Type' => [parent::class, 'Type', null],
        'destination' => [parent::class, 'destination', null],
        'disponibility' => [parent::class, 'disponibility', null],
        'id' => [parent::class, 'id', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
