<?php

namespace Proxies\__CG__\App\Entity\Destination;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Destination extends \App\Entity\Destination\Destination implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'category' => [parent::class, 'category', null],
        "\0".parent::class."\0".'contactInformation' => [parent::class, 'contactInformation', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'idDestination' => [parent::class, 'idDestination', null],
        "\0".parent::class."\0".'image' => [parent::class, 'image', null],
        "\0".parent::class."\0".'location' => [parent::class, 'location', null],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null],
        "\0".parent::class."\0".'parkingSpots' => [parent::class, 'parkingSpots', null],
        "\0".parent::class."\0".'rating' => [parent::class, 'rating', null],
        "\0".parent::class."\0".'routes' => [parent::class, 'routes', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        'category' => [parent::class, 'category', null],
        'contactInformation' => [parent::class, 'contactInformation', null],
        'description' => [parent::class, 'description', null],
        'idDestination' => [parent::class, 'idDestination', null],
        'image' => [parent::class, 'image', null],
        'location' => [parent::class, 'location', null],
        'name' => [parent::class, 'name', null],
        'parkingSpots' => [parent::class, 'parkingSpots', null],
        'rating' => [parent::class, 'rating', null],
        'routes' => [parent::class, 'routes', null],
        'status' => [parent::class, 'status', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
