<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Event extends \App\Entity\Event implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'dateevent' => [parent::class, 'dateevent', null],
        "\0".parent::class."\0".'description' => [parent::class, 'description', null],
        "\0".parent::class."\0".'duration' => [parent::class, 'duration', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'registrations' => [parent::class, 'registrations', null],
        "\0".parent::class."\0".'startEvent' => [parent::class, 'startEvent', null],
        "\0".parent::class."\0".'status' => [parent::class, 'status', null],
        "\0".parent::class."\0".'title' => [parent::class, 'title', null],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null],
        'dateevent' => [parent::class, 'dateevent', null],
        'description' => [parent::class, 'description', null],
        'duration' => [parent::class, 'duration', null],
        'id' => [parent::class, 'id', null],
        'registrations' => [parent::class, 'registrations', null],
        'startEvent' => [parent::class, 'startEvent', null],
        'status' => [parent::class, 'status', null],
        'title' => [parent::class, 'title', null],
        'type' => [parent::class, 'type', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
