# User routes
app_user_profile:
    path: /user/profile
    controller: App\Controller\UserController::profile

app_user_settings:
    path: /user/settings
    controller: App\Controller\UserController::settings

app_user_view:
    path: /user/{id}
    controller: App\Controller\UserController::viewUser
    requirements:
        id: '\d+'

# Admin user management routes
app_admin_users:
    path: /admin/users
    controller: App\Controller\UserController::adminUsersList

app_admin_user_edit:
    path: /admin/users/{id}/edit
    controller: App\Controller\UserController::adminEditUser
    requirements:
        id: '\d+'

app_admin_user_ban:
    path: /admin/users/{id}/ban
    controller: App\Controller\UserController::banUser
    requirements:
        id: '\d+'

app_admin_user_unban:
    path: /admin/users/{id}/unban
    controller: App\Controller\UserController::unbanUser
    requirements:
        id: '\d+'

app_admin_user_change_role:
    path: /admin/users/{id}/change-role
    controller: App\Controller\UserController::changeUserRole
    requirements:
        id: '\d+'

# Claims (Reclamations) routes
app_reclamation_index:
    path: /claims
    controller: App\Controller\ReclamationController::index

app_reclamation_new:
    path: /claims/new
    controller: App\Controller\ReclamationController::new

app_reclamation_show:
    path: /claims/{id}
    controller: App\Controller\ReclamationController::show
    requirements:
        id: '\d+'

app_reclamation_edit:
    path: /claims/{id}/edit
    controller: App\Controller\ReclamationController::edit
    requirements:
        id: '\d+'

app_reclamation_delete:
    path: /claims/{id}/delete
    controller: App\Controller\ReclamationController::delete
    methods: [POST]
    requirements:
        id: '\d+'

app_reclamation_resolve:
    path: /claims/{id}/resolve
    controller: App\Controller\ReclamationController::resolve
    requirements:
        id: '\d+'

app_reclamation_reject:
    path: /claims/{id}/reject
    controller: App\Controller\ReclamationController::reject
    requirements:
        id: '\d+'

app_reclamation_dashboard:
    path: /admin/claims
    controller: App\Controller\ReclamationController::dashboard

app_reclamation_user:
    path: /claims/user/{id}
    controller: App\Controller\ReclamationController::userClaims
    requirements:
        id: '\d+'

# Front-office routes
app_front_home:
    path: /
    controller: App\Controller\Front\FrontController::index

app_front_services:
    path: /services
    controller: App\Controller\Front\FrontController::services

app_front_portfolio:
    path: /portfolio
    controller: App\Controller\Front\FrontController::portfolio

app_front_contact:
    path: /contact
    controller: App\Controller\Front\FrontController::contact

# Admin dashboard
app_dashboard:
    path: /admin
    controller: App\Controller\AdminController::dashboard
