<?php

namespace ContainerRO2GZBO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_9g2mTfJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.9g2mTfJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.9g2mTfJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'destination' => ['privates', '.errored..service_locator.9g2mTfJ.App\\Entity\\Destination\\Destination', NULL, 'Cannot autowire service ".service_locator.9g2mTfJ": it needs an instance of "App\\Entity\\Destination\\Destination" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'destination' => 'App\\Entity\\Destination\\Destination',
            'entityManager' => '?',
        ]);
    }
}
