<?php

namespace ContainerRO2GZBO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Hlgs0qqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hlgs0qq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hlgs0qq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'favorite' => ['privates', '.errored..service_locator.hlgs0qq.App\\Entity\\Destination\\Favorite', NULL, 'Cannot autowire service ".service_locator.hlgs0qq": it needs an instance of "App\\Entity\\Destination\\Favorite" but this type has been excluded in "config/services.yaml".'],
        ], [
            'favorite' => 'App\\Entity\\Destination\\Favorite',
        ]);
    }
}
