<?php

namespace ContainerRO2GZBO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_IfXJfacService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ifXJfac' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.ifXJfac'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'driverRepository' => ['privates', 'App\\Repository\\DriverRepository', 'getDriverRepositoryService', true],
            'transportRepository' => ['privates', 'App\\Repository\\TransportRepository', 'getTransportRepositoryService', true],
        ], [
            'driverRepository' => 'App\\Repository\\DriverRepository',
            'transportRepository' => 'App\\Repository\\TransportRepository',
        ]);
    }
}
