<?php

namespace ContainerRO2GZBO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y818FXaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.y818FXa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.y818FXa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'office' => ['privates', '.errored..service_locator.y818FXa.App\\Entity\\Office', NULL, 'Cannot autowire service ".service_locator.y818FXa": it needs an instance of "App\\Entity\\Office" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'office' => 'App\\Entity\\Office',
        ]);
    }
}
