<?php

namespace ContainerRO2GZBO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_49mrie5Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.49mrie5' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.49mrie5'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'geocodingService' => ['privates', 'App\\Service\\GeocodingService', NULL, 'Cannot autowire service "App\\Service\\GeocodingService": argument "$apiNinjasKey" of method "__construct()" is type-hinted "string", you should configure its value explicitly.'],
        ], [
            'geocodingService' => 'App\\Service\\GeocodingService',
        ]);
    }
}
