<?php

namespace ContainerRO2GZBO;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDriver2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.BaVz79_.App\Entity\Driver' shared service.
     *
     * @return \App\Entity\Driver
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.BaVz79_": it needs an instance of "App\\Entity\\Driver" but this type has been excluded in "config/services.yaml".');
    }
}
