<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRO2GZBO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRO2GZBO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRO2GZBO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRO2GZBO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRO2GZBO\App_KernelDevDebugContainer([
    'container.build_hash' => 'RO2GZBO',
    'container.build_id' => '52c7160e',
    'container.build_time' => 1745275803,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRO2GZBO');
